version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pralsp_mysql
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pralsp

networks:
  pralsp:
    driver: bridge

volumes:
  mysql_data:
